### PR TITLE
apply patches with git instead of patch

### PR DESCRIPTION
**Pull request by TomasTomecek**
For some reason, patch program hates patches generated with git-format-patch

### CODE REVIEW

**Comment by matejak** [comment]
I wouldn't say that `git format-patch` is the best way to generate input for `patch` - I think that `git diff` is designed to serve this purpose (there is even an option `--patch` to `git diff` that is on by default). The `git format-patch` aims at the workflow of sending patches by e-mails.
Wouldn't it be possible to influence whatever generates those patches to do it differently?

**Comment by TomasTomecek** [comment]
> I wouldn't say that `git format-patch` is the best way to generate input for `patch`

Completely agreed, because problems like the one this PR is suppose to solve, arise.

> Wouldn't it be possible to influence whatever generates those patches to do it differently?

It certainly would, we can change that. Let me show you details.

The code we're discussing here is this: https://github.com/packit/packit/blob/main/packit/patches.py#L504

You can see it is pretty complex at this point - so making the process, how patch files are created, configurable would take a few weeks to implement and polish on our side.

I'm wondering what exactly is that you don't like about using git-am to apply patches? I understand that patch and diff programs are good and proven defaults but in the era of "everything is git" I'm personally in favour of using git to create and apply patches as well.

**Comment by matejak** [comment]
I don't see is as a breaking change, I just don't like to deviate from defaults, and having this boilerplate in the spec file or in the packit config lowers the signal to noise ratio.
But I think that it is acceptable in a prototype, so merging.

**Comment by TomasTomecek** [comment]
I created an issue in our tracker to cover this use case/request ^

**Pull request merged**
